### PR TITLE
EL-3781 - Adding Cypress dependencies

### PR DESCRIPTION
**Pull request by ashley-hunter**
Adding dependencies required to run Cypress (https://docs.cypress.io/guides/guides/continuous-integration.html)

@donna-marijne Do I need to update anything else here, eg. bump version number or update release notes?

### CODE REVIEW

**Comment by donna-marijne** [comment]
The version number is fine because the build machine handles rolling it over, however you will need to update the release-notes file at least to remove the `!not-ready-for-release!` line. Thanks.

**Comment by ashley-hunter** [comment]
Thanks, that should be the release notes updated

**Comment by ashley-hunter** [comment]
What is the process in regards to a CI build? Does this require a branch build for example?

**Comment by donna-marijne** [comment]
We can't run end to end builds in this case unfortunately, because the version of the image is hard coded inside official-build.props.

If you want to test this without publishing, you could run a build of this branch and it should get published with the version 1.4.0-EL-3781-Cypress-SNAPSHOT. You could change in official-build.props in the UX Aspects repo and push that up and it should run a build with this new build image.

**Comment by donna-marijne** [comment]
@dermot-hardy I don't recall how to properly test prereleases of this build image in a Jenkins build. I thought we could update SEPG_BUILD_ENV_IMAGE as follows:

https://github.com/UXAspects/UXAspects/pull/1313/files#diff-acea430d4089a5b035c7d59f88098b86

But it seems like it must be published elsewhere, see build log:
https://jenkins.swinfra.net/job/SEPG/job/UXAspects/job/UXAspects~UXAspects~EL-3781-Cypress~CI/lastBuild/console

Could you advise please?

**Comment by dermot-hardy** [comment]
You can get it from `cafinternal/prereleases:buildenv-1.4.0-EL-3781-Cypress-SNAPSHOT`.  `uxaspects/buildenv` is public, so only released builds will be promoted to that location.

**Comment by donna-marijne** [comment]
Great, looks like it's pulled that down now, thank you very much Dermot.

**Pull request closed without merging**
