### PR TITLE
EL-3727: Update version of npm

### PR DESCRIPTION
**Pull request by andyreidz**
We need a newer version of NPM with this fix.
https://github.com/npm/libcipm/pull/1

### CODE REVIEW

**Comment by andyreidz** [comment]
http://sou-jenkins2.swinfra.net:8080/job/UXAspects/job/UXAspects~buildenv-image~EL-3727~CI/

**Comment by andyreidz** [comment]
@ashley-hunter Is install npm@latest safe? It'll always be compatible with the installed version of node?

**Comment by ashley-hunter** [comment]
@andyreidz I don't see why there should be any issue using the latest version of npm, currently the latest version of npm supports all versions of node all the way back to node 6 so there shouldn't be any issues.

**Review by ashley-hunter — APPROVED** [review]
All looks good to me, thanks! Happy to merge unless @dermot-hardy has any additional feedback?

**Pull request merged**
